// Generated by https://quicktype.io

export interface RawResultData {
  FacilityID: string;
  LegacyFacilityID: string;
  OrgFacilityID: string;
  ParentOrgID: string;
  ParentRecAreaID: string;
  FacilityName: string;
  FacilityDescription: string;
  FacilityTypeDescription: FacilityTypeDescription;
  FacilityUseFeeDescription: string;
  FacilityDirections: string;
  FacilityPhone: string;
  FacilityEmail: string | "";
  FacilityReservationURL: string;
  FacilityMapURL: string;
  FacilityAdaAccess: FacilityAdaAccess;
  GEOJSON: Geojson;
  FacilityLongitude: number;
  FacilityLatitude: number;
  Keywords: string;
  StayLimit: string;
  Reservable: boolean;
  Enabled: boolean;
  LastUpdatedDate: string;
}

export interface ResultData {
  id: string
  description: string
  name: string
  mapUrl: string
  type: FacilityTypeDescription
}

export type FacilityAdaAccess = "N" | "";

export type FacilityEmail = string | "";

export enum FacilityTypeDescription {
  Campground = "Campground",
  Facility = "Facility",
}

export interface Geojson {
  TYPE: Type;
  COORDINATES: number[] | null;
}

export enum Type {
  Empty = "",
  Point = "Point",
}
