// Generated by https://quicktype.io

export interface Facility {
  id: string
  description: string
  name: string
  mapUrl: string
  type: FacilityTypeDescription
}

export enum FacilityTypeDescription {
  Campground = "Campground",
  Facility = "Facility",
}