version: "3.0"
services:
  client:
    build: client/
    environment:
      - SERVER_PORT
    ports:
      - "$CLIENT_PORT:$CLIENT_PORT"
    links:
      - server
  server:
    build: server/
    environment:
      - API_KEY
      - SERVER_PORT
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
