version: "3.0"
services:
  client:
    build: client/
    env_file:
      - .env
    ports:
      - "$CLIENT_PORT:$CLIENT_PORT"
    links:
      - server
  server:
    build: server/
    env_file:
      - .env
    environment:
      - API_KEY
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
